services:
  - type: web
    runtime: docker
    name: tskim-portfolio-backend
    plan: free        # 유료 플랜이면 starter, standard 등으로 변경 가능
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: PORT
        value: 8080
